/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usfirst.frc2877.PIDbot2.commands;


import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2877.PIDbot2.Robot;
import org.usfirst.frc2877.PIDbot2.RobotMap;
/**
 *
 * @author ligerbots
 */
public class JoystickDrive extends Command {
    
    public JoystickDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        System.out.println("Drive constructor called");
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("Initialize Drive");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double x = Robot.oi.joystick1.getX();
        double y = Robot.oi.joystick1.getY();
        RobotMap.driveDriveTrain.drive(x,y);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        RobotMap.driveDriveTrain.drive(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
