// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2877.PIDbot2.subsystems;
import org.usfirst.frc2877.PIDbot2.RobotMap;
import org.usfirst.frc2877.PIDbot2.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar cANJag3 = RobotMap.driveCANJag3;
    CANJaguar cANJag1 = RobotMap.driveCANJag1;
    CANJaguar cANJag2 = RobotMap.driveCANJag2;
    CANJaguar cANJag4 = RobotMap.driveCANJag4;
    RobotDrive driveTrain = RobotMap.driveDriveTrain;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public double vC = 1.0;
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
        public void drive(double x, double y) {
        if (driveTrain != null) {
            //this is reversed because of the default variable names, which are moveValue and rotateValue, IN THAT ORDER.
            //since the Y controls going forward, we put Y first. If when you press up the robot turns, undo this.
            driveTrain.arcadeDrive(vC*x, vC*y);
            //Despite what the function looks like it says, you do actually want
            //arcadeDrive.(x,y), not (y,x). AAAARRRRRGH.
        }
    }
}
